name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # or 'master' if that's your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t blackplayer1001/node-app:latest .

      - name: Push Docker image
        run: docker push blackplayer1001/node-app:latest

